version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbooks
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    volumes:
      - guestbook_data:/var/lib/mysql
      - ./guestbook.sql:/docker-entrypoint-initdb.d/guestbook.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080

volumes:
  guestbook_data:
    driver: local
